[tool.poetry]
name = "consultant-bot"
version = "0.1.0"
description = ""
authors = ["Ahmed Rebei"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "2.32.3"
beautifulsoup4 = "^4.12.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
